HT_21/apps/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(prefix=r'users', viewset=views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

api = [
    path("api/", include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

app_name = "account"
urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

urlpatterns += api

HT_21/apps/product/urls.py
from django.urls import path

from . import views

app_name = "product"
urlpatterns = [
    path("upload/", views.ProductUploadView.as_view(), name="upload"),
    path("update/<pk>/", views.ProductUpdateView.as_view(), name="update"),
    path("delete/<pk>/", views.ProductDeleteView.as_view(), name="delete"),
    path("detail/<pk>/", views.ProductDetailView.as_view(), name="detail"),
]

HT_21/apps/products/views/products.py
import logging

from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import ListView

from apps.cart.models import Cart
from apps.products.models import Product, Category

logger = logging.getLogger('django')


class ProductListView(ListView):
    CATEGORIES_KEY = 'categories'
    CATEGORY_CHOICES_KEY = 'select_categories'

    model = Product
    template_name = 'products/index.html'
    context_object_name = 'products'

    def post(self, request, *args, **kwargs):
        if request.user and not request.user.is_authenticated:
            messages.error(request, 'Not access')
            return redirect('index')

        product_id = request.POST.get('product_id')
        if product_id:
            product_quantity = int(request.POST.get('product_quantity'))
            cart = Cart(request)
            self.__product_to_cart(product_id, product_quantity, cart)

        return redirect('index')

    def __product_to_cart(self, product_id: str, product_quantity: int, cart: Cart):
        if cart.is_exist(product_id):
            cart.delete(product_id)
        else:
            try:
                if product_quantity > 0:
                    cart.update(product_id, product_quantity)
                else:
                    raise Exception
            except Exception:
                logger.error(f'added products by id:{product_id} to cart unsuccessful')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        categories = Category.objects.all()
        context[self.CATEGORIES_KEY] = categories

        select_categories = self.request.GET.getlist(self.CATEGORY_CHOICES_KEY)
        if len(select_categories) > 0:
            ids = list(map(int, select_categories))
            products = Product.objects.filter(category__in=ids)
            context[self.context_object_name] = products
            context[self.CATEGORY_CHOICES_KEY] = ids

        return context

HT_21/templates/product/index.html
{% extends 'base.html' %}

{% block base %}

    <button id="aaa" class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasWithBothOptions"
            aria-controls="offcanvasWithBothOptions">Filter
    </button>

    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
         aria-labelledby="offcanvasWithBothOptionsLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Categories:</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            {% if categories %}
                <form method="get">
                    {% for category in categories %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ category.id }}"
                                   id="flexCheckDefault{{ category.id }}" name="select_categories"
                                    {% if select_categories %}
                                   {% if category.id in select_categories %}checked{% endif %}
                                    {% endif %}
                            >
                            <label class="form-check-label" for="flexCheckDefault{{ category.id }}">
                                {{ category.name }}
                            </label>
                        </div>
                    {% endfor %}
                    <div class="row align-items-center my-4">
                        <div class="d-flex align-items-center">
                            <button class="btn bsb-btn-2xl btn-primary" type="submit">Apply</button>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">
        {% if products %}
            {% for product in products %}
                <div class="col d-flex align-items-start">
                    <div class="card shadow-sm h-100">
                        <div class="d-flex justify-content-between card-header fw-bold mb-0 fs-4 text-body-emphasis">
                            <a href="{% url 'product:detail' product.id %}" title="detail">{{ product.id }}</a>
                            {% if request.user.is_superuser %}
                                <div class="d-flex fs-6">
                                    <div>
                                        <a class="bi bi-pencil-square"
                                           href="{% url 'product:update' product.id %}" title="update"></a>
                                    </div>
                                    <div>
                                        <button type="button" class="bg-body-tertiary bi bi-trash mx-1 border-0"
                                                data-bs-toggle="modal" data-bs-target="#confirmModal"
                                                data-bs-whatever="{% url 'product:delete' product.id %}">
                                        </button>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <div class=" card-body">
                            <p class="h-75">{{ product.name }}</p>
                            <p>price: <span class="fw-bold">${{ product.sale_price }}</span></p>
                        </div>
                        <div class="card-footer border-white bg-white">
                            {% if request.user.is_authenticated %}
                                <form method="post">{% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ product.id }}">
                                    <input type="hidden" name="product_quantity" value="1">
                                    {% if product.id in request.session.session_key.cart_key %}
                                        <button type="submit" class="btn btn-warning">Remove from cart</button>
                                    {% else %}
                                        <button type="submit" class="btn btn-primary">Add to cart</button>
                                    {% endif %}
                                </form>
                            {% endif %}
                            <p>
                                <span class="fs-6 fw-light fst-italic">
                                {% if product.category %}
                                    {{ product.category.name }}
                                {% else %}
                                    -
                                {% endif %}
                            </span>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="confirmModalLabel">Confirm delete product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="confirmModalForm" method="post" action="">{% csrf_token %}
                    <div class="modal-body">
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">Confirm</button>
                        </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        const exampleModal = document.getElementById('confirmModal')
        if (exampleModal) {
            exampleModal.addEventListener('show.bs.modal', event => {
                const button = event.relatedTarget
                const recipient = button.getAttribute('data-bs-whatever')
                $('#confirmModalForm').attr('action', recipient)
            })
        }
    </script>
{% endblock %}

HT_21/templates/product/update.html
{% extends 'base.html' %}

{% block base %}
    {% if product %}
        <div class="my-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="col-2">
                            <h5 class="card-subtitle mb-2" title="id">
                                <span class="text-secondary text-opacity-50 text-end">Product:</span>
                                {{ product.id }}
                            </h5>
                        </div>
                        <div class="d-flex">
                            <form method="post"
                                  action="{% url 'product:upload' %}?next={{ request.path }}"> {% csrf_token %}
                                <input type="hidden" name="ids" value="{{ view.kwargs.pk }}">
                                <button type="submit" class="btn btn-warning mb-3">Upload current product</button>
                            </form>
                        </div>
                    </div>
                    <form method="post"
                          action="{% url 'product:update' view.kwargs.pk %}?next={{ request.path }}">{% csrf_token %}
                        <table class="table table-borderless">
                            <tbody>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">brand name:</td>
                                <td class="col-auto">
                                    <input class="form-control" type="text" placeholder="input value" aria-label=""
                                           name="brand_name" value="{{ form.brand_name.value }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">product name:</td>
                                <th scope="row">
                                    <input class="form-control" type="text" placeholder="input value" aria-label=""
                                           name="name" value="{{ form.name.value }}">
                                </th>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">main image url:</td>
                                <td>
                                    <input class="form-control" type="text" placeholder="input value" aria-label=""
                                           name="main_image_url" value="{{ form.main_image_url.value }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">product url:</td>
                                <td>
                                    <input class="form-control" type="text" placeholder="input value" aria-label=""
                                           name="url" value="{{ form.url.value }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">regular price:</td>
                                <th scope="row">
                                    <input class="form-control" type="number" min="0.00" max="100000.00" step="0.01"
                                           placeholder="input value" aria-label=""
                                           name="regular_price" value="{{ form.regular_price.value }}">
                                </th>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">sale rice:</td>
                                <th scope="row">
                                    <input class="form-control" type="number" min="0.00" max="100000.00" step="0.01"
                                           placeholder="input value" aria-label=""
                                           name="sale_price" value="{{ form.sale_price.value }}">
                                </th>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">default seller:</td>
                                <td>
                                    <input class="form-control" type="text" placeholder="input value" aria-label=""
                                           name="default_seller_id" value="{{ form.default_seller_id.value }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">store id:</td>
                                <td>
                                    <input class="form-control" type="text" placeholder="input value" aria-label=""
                                           name="store_id" value="{{ form.store_id.value }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="col-2 text-secondary text-opacity-50 text-end">category:</td>
                                <td>
                                    <select class="form-control" name="category" id="category" aria-label="">
                                        {% for option in form.category %}
                                            {{ option }}
                                        {% endfor %}
                                    </select>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="col p-3">
                            <label for="descriptionTextarea" class="form-label fw-bold">Description:</label>
                            <textarea class="form-control" id="descriptionTextarea" rows="3" name="description">
                            {{ form.description.value | safe }}
                        </textarea>
                        </div>
                        <div class="col p-3">
                            <button type="submit" class="btn btn-primary mb-3">Update</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    {% endif %}

{% endblock %}