HT_24/apps/cart/api/urls.py
from django.urls import path

from apps.cart.api.views import CartApiView

app_name = 'api_cart'
urlpatterns = [
    path('', CartApiView.as_view(), name='cart')
]

HT_24/apps/products/api/urls.py
from django.urls import path, include
from rest_framework import routers

from apps.products.api import views

router = routers.DefaultRouter()
router.register(prefix=r'categories', viewset=views.CategoryViewSet, basename='categories')
router.register(prefix=r'brands', viewset=views.BrandAPIView, basename='brands')
router.register(prefix=r'products', viewset=views.ProductViewSet, basename='products')
router.register(prefix=r'tags', viewset=views.TagViewSet, basename='tags')

app_name = "api_products"
urlpatterns = [
    path("", include(router.urls)),
]

HT_24/apps/products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    path("upload/", views.ProductUploadView.as_view(), name="upload"),
    path("update/<pk>/", views.ProductUpdateView.as_view(), name="update"),
    path("delete/<pk>/", views.ProductDeleteView.as_view(), name="delete"),
    path("<pk>/", views.ProductDetailView.as_view(), name="detail"),
]

HT_24/apps/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.products.views.list import ProductListView

api_urls = [
    path("accounts/", include("apps.accounts.api_urls")),
    path("products/", include("apps.products.api.urls")),
    path("cart/", include("apps.cart.api.urls")),
]

urlpatterns = [
    path("", ProductListView.as_view(), name="index"),

    path("accounts/", include("apps.accounts.urls")),
    path("cart/", include("apps.cart.urls")),
    path("products/", include("apps.products.urls")),

    path('admin/', admin.site.urls, name="admin"),

    path("api/", include(api_urls)),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

HT_24/apps/products/models/brand.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Brand(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)

    def __str__(self):
        return self.name

HT_24/apps/products/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

HT_24/apps/products/models/product.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    id = models.CharField(_('id'), max_length=12, primary_key=True)

    name = models.CharField(_('name'), max_length=255)
    main_image_url = models.CharField(_('image url'), max_length=255)
    description = models.TextField(_('description'), )
    url = models.CharField(_('url'), max_length=255)

    regular_price = models.DecimalField(_('regular price'), max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(_('sale price'), max_digits=10, decimal_places=2)

    default_seller_id = models.CharField(_('default seller id'), max_length=12)
    store_id = models.IntegerField(_('store id'), )

    tags = models.ManyToManyField(
        'Tag',
        blank=True,
        related_name='products',
    )

    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='products'
    )

    brand = models.ForeignKey(
        'Brand',
        on_delete=models.PROTECT,
        blank=True,
        related_name='products'
    )

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
        # if not self.slug:
        #     self.slug = slugify(str(f''))
        # super().save(*args, **kwargs)

HT_24/apps/products/models/tag.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Tag(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)

    def __str__(self):
        return self.name

HT_24/apps/products/forms.py
from django import forms


class ProductForm(forms.Form):
    ids = forms.CharField(
        min_length=10,
        max_length=120,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter the ids separated by comma',
            }
        )
    )

    def is_valid(self):
        if not super().is_valid():
            return False

        ids_str = self.cleaned_data['ids']
        ids = [item.strip() for item in ids_str.split(sep=',')]

        if len(ids) > 10:
            return False

        return all(self.__is_valid_id(_id) for _id in ids)

    def __is_valid_id(self, _id: str):
        if len(_id) == 0:
            return False

        return all(i.isdigit() or i.isalpha() for i in _id)

HT_24/apps/products/api/views/brand.py
from drf_spectacular.utils import extend_schema
from rest_framework.viewsets import ModelViewSet

from apps.products.api.permissions import DefaultPermission
from apps.products.api.tags import BRAND_TAG
from apps.products.models import Brand
from apps.products.serializers import BrandSerializer


@extend_schema(
    tags=[BRAND_TAG],
)
class BrandAPIView(ModelViewSet):
    queryset = Brand.objects.all().order_by('id')
    serializer_class = BrandSerializer
    permission_classes = [DefaultPermission]

HT_24/apps/products/api/views/category.py
from drf_spectacular.utils import extend_schema
from rest_framework.viewsets import ModelViewSet

from apps.products.api.permissions import DefaultPermission
from apps.products.api.tags import CATEGORY_TAG
from apps.products.models import Category
from apps.products.serializers import CategorySerializer


@extend_schema(
    tags=[CATEGORY_TAG],
)
class CategoryViewSet(ModelViewSet):
    queryset = Category.objects.all().order_by('id')
    serializer_class = CategorySerializer
    permission_classes = [DefaultPermission]

HT_24/apps/products/api/views/product.py
import logging

from drf_spectacular.utils import extend_schema, OpenApiResponse, OpenApiExample
from rest_framework import status
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from apps.products.api.permissions import DefaultPermission
from apps.products.api.tags import PRODUCT_TAG
from apps.products.models import Product
from apps.products.serializers import ProductSerializer
from apps.tasks import scraping_items

logger = logging.getLogger('django')


@extend_schema(
    tags=[PRODUCT_TAG],
)
class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all().order_by('id')
    serializer_class = ProductSerializer
    permission_classes = [DefaultPermission]

    @extend_schema(
        responses={
            status.HTTP_204_NO_CONTENT: OpenApiResponse(
                description='Task for scraping products by IDs run successfully',
                response=None,
            ),
            status.HTTP_400_BAD_REQUEST: OpenApiResponse(
                description='Exception run task of scraping',
                response=None,
            ),
        },
        methods=["POST"],
        examples=[
            OpenApiExample(
                'Example Value',
                value={
                    "ids": "string of ids separated by comma"
                },
            ),
        ],
    )
    def create(self, request, *args, **kwargs):
        if request.method.upper() != 'POST':
            return super().create(request, *args, **kwargs)

        try:
            ids_str = ''.join(ch for ch in str(dict(request.data).get('ids')) if ch not in '"\'[]')
            ids = [item.strip() for item in ids_str.split(',')]
            scraping_items.apply_async(ids=ids)
            return Response(status=status.HTTP_204_NO_CONTENT)
        except:
            logger.error(f"scraping process run unsuccessful")
            return Response(status=status.HTTP_400_BAD_REQUEST)

HT_24/apps/products/api/views/tag.py
from drf_spectacular.utils import extend_schema
from rest_framework.viewsets import ModelViewSet

from apps.products.api.permissions import DefaultPermission
from apps.products.api.tags import TAG_TAG
from apps.products.models import Tag
from apps.products.serializers import TagSerializer


@extend_schema(
    tags=[TAG_TAG],
)
class TagViewSet(ModelViewSet):
    queryset = Tag.objects.all().order_by('id')
    serializer_class = TagSerializer
    permission_classes = [DefaultPermission]

HT_24/apps/products/views/delete.py
import logging

from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from apps.products.models import Product

logger = logging.getLogger('django')


class ProductDeleteView(generic.DeleteView):
    model = Product
    success_url = reverse_lazy("index")

    def get(self, request, *args, **kwargs):
        if request.user and request.user.is_superuser:
            return super().get(request, *args, **kwargs)
        else:
            messages.error(request, 'Not access for delete')
            return redirect('index')

    def post(self, request, *args, **kwargs):
        if not request.user and not request.user.is_superuser:
            redirect('products:update')

        return super().post(request, *args, **kwargs)

HT_24/apps/products/views/detail.py
from django.views.generic import DetailView

from apps.products.models import Product


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'product'

HT_24/apps/products/views/list.py
import logging

from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import ListView

from apps.cart.models import Cart
from apps.products.models import Product, Category

logger = logging.getLogger('django')


class ProductListView(ListView):
    CATEGORIES_KEY = 'categories'
    CATEGORY_CHOICES_KEY = 'select_categories'

    model = Product
    template_name = 'products/index.html'
    context_object_name = 'products'

    def post(self, request, *args, **kwargs):
        if request.user and not request.user.is_authenticated:
            messages.error(request, 'Not access')
            return redirect('index')

        product_id = request.POST.get('product_id')
        if product_id:
            product_quantity = int(request.POST.get('product_quantity'))
            cart = Cart(request)

            if cart.is_exist(product_id):
                cart.delete(product_id)
            else:
                if product_quantity > 0:
                    cart.update(product_id, product_quantity)

        return redirect('index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        categories = Category.objects.all()
        context[self.CATEGORIES_KEY] = categories

        select_categories = self.request.GET.getlist(self.CATEGORY_CHOICES_KEY)
        if len(select_categories) > 0:
            ids = list(map(int, select_categories))
            products = Product.objects.filter(category__in=ids)
            context[self.context_object_name] = products
            context[self.CATEGORY_CHOICES_KEY] = ids

        return context

HT_24/apps/products/views/update.py
import logging

from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from apps.products.models import Product

logger = logging.getLogger('django')


class ProductUpdateView(UpdateView):
    model = Product
    fields = [
        'brand',
        'name',
        'main_image_url',
        'url',
        'regular_price',
        'sale_price',
        'default_seller_id',
        'store_id',
        'description',
        'category',
    ]
    template_name = 'products/update.html'
    success_url = reverse_lazy("index")

    def get(self, request, *args, **kwargs):
        if request.user and request.user.is_superuser:
            return super().get(request, *args, **kwargs)
        else:
            messages.error(request, 'Not access for update')
            return redirect('index')

    def get_success_url(self):
        redirect_url = self.request.GET.get('next')
        if redirect_url:
            self.success_url = redirect_url
        messages.info(self.request, 'Update success')

        return super().get_success_url()

    def post(self, request, *args, **kwargs):
        if not request.user and not request.user.is_superuser:
            return redirect('products:update')

        return super().post(request, *args, **kwargs)

HT_24/apps/products/views/upload.py
import logging

from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import FormView

from apps.products.forms import ProductForm
from apps.tasks import scraping_items

logger = logging.getLogger('django')


class ProductUploadView(FormView):
    template_name = 'products/upload.html'
    form_class = ProductForm

    def get(self, request, *args, **kwargs):
        if request.user and request.user.is_superuser:
            return super().get(request, *args, **kwargs)
        else:
            messages.error(request, 'Not access')
            return redirect('index')

    def post(self, request, *args, **kwargs):
        if not request.user and not request.user.is_superuser:
            return redirect('products:upload')

        if request.user and request.user.is_superuser:
            form = ProductForm(request.POST)
            if form.is_valid():
                ids_str = form.cleaned_data['ids']
                ids = ids_str.split(',')
                scraping_items.delay(ids=ids)
                messages.info(request, 'Products send to scraping successfully')
            else:
                messages.error(request, 'Form data unsuccessfully')

        redirect_url = request.GET.get('next')
        if redirect_url:
            return redirect(redirect_url)
        else:
            return redirect('products:upload')

HT_24/templates/products/detail.html
{% extends 'base.html' %}

{% block base %}
    {% if product %}
        <div class="my-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="col-2">
                            <h5 class="card-subtitle mb-2" title="id">
                                <span class="text-secondary text-opacity-50 text-end">Product:</span>
                                {{ product.id }}
                            </h5>
                        </div>
                    </div>
                    <table class="table">
                        <tbody>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">brand name:</td>
                            <td>{{ product.brand.name }}</td>
                        </tr>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">product name:</td>
                            <th scope="row">{{ product.name }}</th>
                        </tr>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">main image url:</td>
                            <td><a href="{{ product.main_image_url }}">{{ product.main_image_url }}</a></td>
                        </tr>

                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">product url:</td>
                            <td>{{ product.url }}</td>
                        </tr>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">regular price:</td>
                            <th scope="row">{{ product.regular_price }}</th>
                        </tr>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">sale rice:</td>
                            <th scope="row">{{ product.sale_price }}</th>
                        </tr>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">default seller:</td>
                            <td>{{ product.default_seller_id }}</td>
                        </tr>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">store id:</td>
                            <td>{{ product.store_id }}</td>
                        </tr>
                        <tr>
                            <td class="text-secondary text-opacity-50 text-end">category:</td>
                            <td>{{ product.category }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col p-3">
                    <label for="descriptionTextarea" class="form-label fw-bold">Description:</label>
                    <div class="form-control" id="descriptionTextarea">
                        {{ product.description | safe }}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

HT_24/templates/products/index.html
{% extends 'base.html' %}
{% load static %}

{% block base %}
    <button id="aaa" class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasWithBothOptions"
            aria-controls="offcanvasWithBothOptions">Filter
    </button>

    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
         aria-labelledby="offcanvasWithBothOptionsLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Categories:</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            {% if categories %}
                <form method="get">
                    {% for category in categories %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ category.id }}"
                                   id="flexCheckDefault{{ category.id }}" name="select_categories"
                                    {% if select_categories %}
                                   {% if category.id in select_categories %}checked{% endif %}
                                    {% endif %}
                            >
                            <label class="form-check-label" for="flexCheckDefault{{ category.id }}">
                                {{ category.name }}
                            </label>
                        </div>
                    {% endfor %}
                    <div class="row align-items-center my-4">
                        <div class="d-flex align-items-center">
                            <button class="btn bsb-btn-2xl btn-primary" type="submit">Apply</button>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">
        {% if products %}
            {% for product in products %}
                <div class="col d-flex align-items-start">
                    <div class="card shadow-sm h-100 w-100">
                        <div class="d-flex justify-content-between card-header fw-bold mb-0 fs-4 text-body-emphasis">
                            <a href="{% url 'products:detail' product.id %}" title="detail">{{ product.id }}</a>
                            {% if request.user.is_superuser %}
                                <div class="d-flex fs-6">
                                    <div>
                                        <a class="bi bi-pencil-square"
                                           href="{% url 'products:update' product.id %}" title="update"></a>
                                    </div>
                                    <div>
                                        <button type="button" class="bg-body-tertiary bi bi-trash mx-1 border-0"
                                                data-bs-toggle="modal" data-bs-target="#confirmModal"
                                                data-bs-whatever="{% url 'products:delete' product.id %}">
                                        </button>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <div class=" card-body">
                            <p class="h-75">{{ product.name }}</p>
                            <p>price: <span class="fw-bold">${{ product.sale_price }}</span></p>
                        </div>
                        <div class="card-footer border-white bg-white">
                            {% if request.user.is_authenticated %}

                                {#                                <input type="hidden" name="product_id" value="{{ product.id }}">#}
                                {#                                <input type="hidden" name="product_quantity" value="1">#}

                                {% load inside %}
                                {% if request.session.session_key.cart_key %}
                                    {% if product.id|inside:request.session.session_key.cart_key %}
                                        <button class="btn btn-warning addCartButton"
                                                data-product_id="{{ product.id }}">Remove from cart
                                        </button>
                                    {% else %}
                                        <button class="btn btn-primary addCartButton"
                                                data-product_id="{{ product.id }}">Add to cart
                                        </button>
                                    {% endif %}
                                {% else %}
                                    <button class="btn btn-primary addCartButton"
                                            data-product_id="{{ product.id }}">Add to cart
                                    </button>
                                {% endif %}

                            {% endif %}
                            <p>
                                <span class="fs-6 fw-light fst-italic">
                                {% if product.category %}
                                    {{ product.category.name }}
                                {% else %}
                                    -
                                {% endif %}
                            </span>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="confirmModalLabel">Confirm delete product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="confirmModalForm" method="post" action="">{% csrf_token %}
                    <div class="modal-body">
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">Confirm</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script>
        const exampleModal = document.getElementById('confirmModal')
        if (exampleModal) {
            exampleModal.addEventListener('show.bs.modal', event => {
                const button = event.relatedTarget
                const recipient = button.getAttribute('data-bs-whatever')
                $('#confirmModalForm').attr('action', recipient)
            })
        }
    </script>

    <script>
        window.cartApiUrl = "{% url 'api_cart:cart' %}"
    </script>

    {% csrf_token %}
    <script src="{% static 'js/cart.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
{% endblock %}

HT_24/templates/products/upload.html
{% extends 'base.html' %}

{% block base %}
    <div class="my-3">
        <form  method="post">{% csrf_token %}
            <div class="form-floating mb-3">
                {{ form.ids }}
                <label for="id_ids">Enter the ids separated by comma</label>
            </div>
            <div id="formHelpBlock" class="form-text">
                Ids must be in format 'A123456789' and separate by comma. Max items is 10 and length is 120. Example:
                A123456789,A111222333,...
            </div>
            <button type="submit" class="btn btn-primary my-3">Do</button>
        </form>
    </div>
{% endblock %}